### PR TITLE
new updates

### PR DESCRIPTION
**Pull request by wguanicedew**
(1) use 'StatefulSet' to replace 'Deployment': With deployment, all pods will share the same mounted directory. With statefulset, different pods will use different mounted directory with volumeClaimTemplate. StatefulSet requires a defined service, that's why in jedi I added a fake service.
(2) For manually created PV, added 'reclaim policy' to be 'deleted', to make sure the PV can be deleted automatically. Without it at CERN k8s cluster, the PV is created at local host. Every time when there is a pod movement (from one machine to another machine), the pod will leave a PV in the original host. Then after some time, all hosts are full and no pods can get PVs.
(3) update lsst pilot template to enable realtime logging.
(4) move harvester condor_logs out of panda logs: the plan is to use shared pvc for condor_logs and per-host pvc for panda logs. For condor_logs, the plan is to define '"logDir": "/var/log/panda/condor_logs/${hostname}"' and '"logBaseURL": "https://panda-dev-server/condor_logs/${hostname}"'. So that the condor_logs can be exported from all harvester pods.
(5) merge iDDS daemon and rest to one pod, remove the daemon chart
(6) update the ingress timeout for panda/idds/bigmon.

### CODE REVIEW

**Comment by tmaeno** [comment]
Hi @xzhao87
This is required to have multiple replicas for each service. Can you test at BNL OKD, as I suppose that Wen tested at CERN and SLAC?

**Comment by wguanicedew** [comment]
yes. I tested it at both CERN and SLAC. With statefulset, the pod name is not random characters. The pod names are indexed with numbers.

`[wguan@sdfrome001 ~]$ kubectl get all -n panda
NAME                                         READY   STATUS    RESTARTS   AGE
pod/bigmon-dev-main-0                        1/1     Running   0          24h
pod/bigmon-dev-main-1                        1/1     Running   0          24h
pod/harvester-dev-0                          1/1     Running   0          24h
pod/harvester-dev-1                          1/1     Running   0          24h
pod/harvester-dev-mariadb-69bb5b495b-9vjjz   1/1     Running   0          24h
pod/iam-dev-main-5b9cc97898-pfhwj            1/1     Running   2          31d
pod/iam-dev-mariadb-78c9c9fd8d-6gppq         1/1     Running   0          31d
pod/idds-dev-postgres-84bc4d45d6-bkb4g       1/1     Running   0          24h
pod/idds-dev-rest-0                          1/1     Running   0          24h
pod/idds-dev-rest-1                          1/1     Running   0          24h
pod/msgsvc-dev-activemq-7c47bb7d7-5wd7k      1/1     Running   0          8d
pod/panda-dev-jedi-0                         1/1     Running   0          24h
pod/panda-dev-jedi-1                         1/1     Running   0          24h
pod/panda-dev-postgres-5f87b89477-s29b4      1/1     Running   0          24h
pod/panda-dev-server-0                       1/1     Running   0          24h
pod/panda-dev-server-1                       1/1     Running   0          24h`

**Comment by xzhao87** [comment]
OK sure, I will test it on BNL OKD.

**Comment by xzhao87** [comment]
I tested it on BNL OKD, set up 2 replicas of several components as Wen did. ran 5k short jobs overnight, works fine. 

A couple of things noticed: 
1) there are still problem accessing some of the condor logs when multiple replicas of harvester are running in parallel, but I think this is work in progress, as indicated in Wen's comments. 
2) in order to use the multiple replicas, I added "replicaCount:" line to the values-sphenix.yaml files in several components. It would be good to have the replicaCount line in those values-sphenix.yaml files in the git repo, so it's clear where to config the feature. We can set it to be "replicaCount: 1" as default.  

While running the 5k test jobs, I also checked log files of the pods, some of the errors are listed below, they may
not be related to this multiple replicas comments, but I will just mention them below :  

a) in the harvester panda-service_monitor.log, it complains about "/var/log/harvester/panda_harvester.pid" doesn't exist, I guess this is defined in the panda_harvester.cfg file inside the harvester image, which uses the default value when the image was built. But inside the container, the real pid file is located at /var/run/panda/panda_harvester.pid

b) on the panda server pods, several log files show errors (below is the list of files). Not to make 
this reply too long, I won't give details of them here, some of them may be harmless or transient. 
Anyway it would be good if you could double check them : 

$ grep -iR " ERROR " -l /var/log/panda/*.log 
/var/log/panda/panda-Adder.log
/var/log/panda/panda-add_sub.log
/var/log/panda/panda-Closer.log
/var/log/panda/panda-daemons.log
/var/log/panda/panda-DBProxyFiltered.log
/var/log/panda/panda-DBProxy.log
/var/log/panda/panda-Initializer.log
/var/log/panda/panda-JobDispatcher.log
/var/log/panda/panda-MailUtils.log
/var/log/panda/panda-msg_bkr_utils.log

c) In the jedi pod, several log files show error messages as well, below is the list of files : 

$ grep -l ERROR /var/log/panda/*.log
/var/log/panda/panda-JediDBProxy.log
/var/log/panda/panda-JediDBProxyFiltered.log
/var/log/panda/panda-JobGenerator.log
/var/log/panda/panda-PostProcessor.log

Thanks!
Xin

**Comment by wguanicedew** [comment]
(1) the pidfile problem is fixed in the configmap json file.
(2) change the logDir and logBaseUrl to have hostname (wait for this one https://github.com/HSF/harvester/pull/167). For test, you can use 'repository: ghcr.io/wguanicedew/harvester, tag: "wguan0.0.11"'
(3) define submissionHost to be '$hostname': by default, all jobs are marked as submissionHost='LOCAL'.
(4) for panda and jedi 'ERROR' messages, many of them can be ignored, such as 'cannot get lock'.

**Comment by wguanicedew** [comment]
I did some fixes: (1) move condor spool information to persistent storage. (2) define the condor pool.
I tested them with wguan0.0.16 and it works ok at SLAC.

**Comment by xzhao87** [comment]
I tested this on BNL OKD, using wguan0.0.17 image ([pr#168](https://github.com/HSF/harvester/pull/168)), it works fine.

**Pull request merged**
